# 関連時系列を使ったバージョン

# Kaggle提出用ファイルを作成する

# 1.S3からforecast結果をdownload

In [2]:
!aws s3 cp --recursive s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/ ../result_forecast_tgt_rlt/

download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part0.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part0.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/_CHECK to ../result_forecast_tgt_rlt/_CHECK
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part100.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part100.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/_SUCCESS to ../result_forecast_tgt_rlt/_SUCCESS
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part1.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part1.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part10.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part10.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part105.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part105.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part101.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part101.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part106.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part106.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part102.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part102.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part108.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part108.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part103.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part103.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part11.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part11.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part110.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part110.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part111.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part111.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part104.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part104.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part107.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part107.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part112.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part112.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part109.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part109.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part116.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part116.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part117.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part117.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part115.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part115.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part113.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part113.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part114.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part114.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part119.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part119.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part120.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part120.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part121.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part121.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part118.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part118.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part125.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part125.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part12.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part12.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part126.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part126.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part123.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part123.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part124.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part124.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part122.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part122.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part130.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part130.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part129.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part129.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part128.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part128.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part131.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part131.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part13.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part13.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part127.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part127.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part132.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part132.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part136.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part136.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part135.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part135.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part134.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part134.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part133.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part133.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part139.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part139.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part137.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part137.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part138.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part138.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part14.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part14.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part140.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part140.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part143.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part143.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part142.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part142.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part141.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part141.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part144.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part144.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part145.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part145.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part15.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part15.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part149.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part149.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part146.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part146.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part147.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part147.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part148.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part148.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part150.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part150.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part152.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part152.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part151.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part151.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part153.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part153.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part154.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part154.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part156.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part156.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part155.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part155.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part157.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part157.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part158.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part158.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part161.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part161.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part159.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part159.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part16.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part16.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part160.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part160.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part162.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part162.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part164.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part164.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part166.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part166.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part165.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part165.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part167.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part167.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part163.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part163.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part170.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part170.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part17.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part17.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part168.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part168.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part171.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part171.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part172.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part172.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part169.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part169.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part174.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part174.csv
download: s3://work-kaggle-ohio/store-sales-time-series-forecasting/export_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part175.csv to ../result_forecast_tgt_rlt/kaggle_sales_tgt_rlt_2022-01-20T13-43-27Z_part175.csv

## データ結合

In [3]:
import glob
import pandas as pd

df = pd.DataFrame()

files = glob.glob("../result_forecast_tgt_rlt/*.csv")
for file in files:
    #print(file)
    df_tmp = pd.read_csv(file)
    df = pd.concat([df,df_tmp]).reset_index(drop=True)

In [4]:
df

,item_id,date,store_nbr,p10,p50,p90
0,beverages,2017-08-16T00:00:00Z,36,2262.031021,3009.069656,3822.574292
1,beverages,2017-08-17T00:00:00Z,36,2256.266597,3077.821545,4020.284493
2,beverages,2017-08-18T00:00:00Z,36,2272.565834,3070.466037,4049.060240
3,beverages,2017-08-19T00:00:00Z,36,2764.037151,3630.943688,4531.584225
4,beverages,2017-08-20T00:00:00Z,36,2828.150709,3775.789176,4765.177642
...,...,...,...,...,...,...
28507,seafood,2017-08-27T00:00:00Z,28,2.164328,7.638127,13.111927
28508,seafood,2017-08-28T00:00:00Z,28,-1.529725,3.950719,9.431163
28509,seafood,2017-08-29T00:00:00Z,28,-0.604704,4.882388,10.369480
28510,seafood,2017-08-30T00:00:00Z,28,-2.931443,2.562277,8.055997
28511,seafood,2017-08-31T00:00:00Z,28,-2.990883,2.509457,8.009797

## 提出用ファイルに整形

In [5]:
df_sub = pd.read_csv('../input/sample_submission.csv')

In [6]:
df_sub

            id  sales
0      3000888    0.0
1      3000889    0.0
2      3000890    0.0
3      3000891    0.0
4      3000892    0.0
...        ...    ...
28507  3029395    0.0
28508  3029396    0.0
28509  3029397    0.0
28510  3029398    0.0
28511  3029399    0.0

[28512 rows x 2 columns]

In [7]:
df_test = pd.read_csv('../input/test.csv')

In [9]:
print(df_test.nunique())
print(df_test['date'].min())
print(df_test['date'].max())
print(54*33*16)

id             28512
date              16
store_nbr         54
family            33
onpromotion      212
dtype: int64
2017-08-16
2017-08-31
28512

# dfを提出用に加工していく

In [11]:
df

,item_id,date,store_nbr,p10,p50,p90
0,beverages,2017-08-16T00:00:00Z,36,2262.031021,3009.069656,3822.574292
1,beverages,2017-08-17T00:00:00Z,36,2256.266597,3077.821545,4020.284493
2,beverages,2017-08-18T00:00:00Z,36,2272.565834,3070.466037,4049.060240
3,beverages,2017-08-19T00:00:00Z,36,2764.037151,3630.943688,4531.584225
4,beverages,2017-08-20T00:00:00Z,36,2828.150709,3775.789176,4765.177642
...,...,...,...,...,...,...
28507,seafood,2017-08-27T00:00:00Z,28,2.164328,7.638127,13.111927
28508,seafood,2017-08-28T00:00:00Z,28,-1.529725,3.950719,9.431163
28509,seafood,2017-08-29T00:00:00Z,28,-0.604704,4.882388,10.369480
28510,seafood,2017-08-30T00:00:00Z,28,-2.931443,2.562277,8.055997
28511,seafood,2017-08-31T00:00:00Z,28,-2.990883,2.509457,8.009797

In [12]:
df['family'] = df['item_id'].str.upper()
df['date'] = df['date'].str[0:10]
df['sales'] = df['p50']

In [13]:
df

,item_id,date,store_nbr,p10,p50,p90,family,sales
0,beverages,2017-08-16,36,2262.031021,3009.069656,3822.574292,BEVERAGES,3009.069656
1,beverages,2017-08-17,36,2256.266597,3077.821545,4020.284493,BEVERAGES,3077.821545
2,beverages,2017-08-18,36,2272.565834,3070.466037,4049.060240,BEVERAGES,3070.466037
3,beverages,2017-08-19,36,2764.037151,3630.943688,4531.584225,BEVERAGES,3630.943688
4,beverages,2017-08-20,36,2828.150709,3775.789176,4765.177642,BEVERAGES,3775.789176
...,...,...,...,...,...,...,...,...
28507,seafood,2017-08-27,28,2.164328,7.638127,13.111927,SEAFOOD,7.638127
28508,seafood,2017-08-28,28,-1.529725,3.950719,9.431163,SEAFOOD,3.950719
28509,seafood,2017-08-29,28,-0.604704,4.882388,10.369480,SEAFOOD,4.882388
28510,seafood,2017-08-30,28,-2.931443,2.562277,8.055997,SEAFOOD,2.562277
28511,seafood,2017-08-31,28,-2.990883,2.509457,8.009797,SEAFOOD,2.509457

In [14]:
df_mrg = pd.merge(df_test, df, how='left', on=['date', 'store_nbr', 'family'])

In [16]:
df_mrg[['id' ,'sales']].to_csv('../submit/sub_forecast_tgt_rlt.csv', index=False)

# !!!!!! 予測期間16日じゃないかあああああああ

In [13]:
df_test['item_id'] = df_test['family'].str.lower()

In [14]:
df_test

,id,date,store_nbr,family,onpromotion,item_id
0,3000888,2017-08-16,1,AUTOMOTIVE,0,automotive
1,3000889,2017-08-16,1,BABY CARE,0,baby care
2,3000890,2017-08-16,1,BEAUTY,2,beauty
3,3000891,2017-08-16,1,BEVERAGES,20,beverages
4,3000892,2017-08-16,1,BOOKS,0,books
...,...,...,...,...,...,...
28507,3029395,2017-08-31,9,POULTRY,1,poultry
28508,3029396,2017-08-31,9,PREPARED FOODS,0,prepared foods
28509,3029397,2017-08-31,9,PRODUCE,1,produce
28510,3029398,2017-08-31,9,SCHOOL AND OFFICE SUPPLIES,9,school and office supplies
28511,3029399,2017-08-31,9,SEAFOOD,0,seafood

In [15]:
df.head()

  item_id                  date  store_nbr       p10       p50       p90
0  beauty  2017-08-16T00:00:00Z         25  0.750166  2.789812  4.635010
1  beauty  2017-08-17T00:00:00Z         25 -0.135176  2.517841  4.884029
2  beauty  2017-08-18T00:00:00Z         25  0.326958  4.131533  7.308528
3  beauty  2017-08-19T00:00:00Z         25  0.329145  3.246138  7.528454
4  beauty  2017-08-20T00:00:00Z         25  0.874725  4.269231  6.614688

In [16]:
df['date'] = df['date'].str.replace('T',' ').str.replace(' 00:00:00Z','')

In [17]:
df['sales'] = df['p50']

In [18]:
df.head()

  item_id        date  store_nbr       p10       p50       p90     sales
0  beauty  2017-08-16         25  0.750166  2.789812  4.635010  2.789812
1  beauty  2017-08-17         25 -0.135176  2.517841  4.884029  2.517841
2  beauty  2017-08-18         25  0.326958  4.131533  7.308528  4.131533
3  beauty  2017-08-19         25  0.329145  3.246138  7.528454  3.246138
4  beauty  2017-08-20         25  0.874725  4.269231  6.614688  4.269231

In [19]:
pd.merge(df, df_test[['date','item_id','store_nbr','id']], how='left', on=['date','item_id','store_nbr'])

,item_id,date,store_nbr,p10,p50,p90,sales,id
0,beauty,2017-08-16,25,0.750166,2.789812,4.635010,2.789812,3001451
1,beauty,2017-08-17,25,-0.135176,2.517841,4.884029,2.517841,3003233
2,beauty,2017-08-18,25,0.326958,4.131533,7.308528,4.131533,3005015
3,beauty,2017-08-19,25,0.329145,3.246138,7.528454,3.246138,3006797
4,beauty,2017-08-20,25,0.874725,4.269231,6.614688,4.269231,3008579
...,...,...,...,...,...,...,...,...
26725,seafood,2017-08-26,5,4.574191,10.245558,14.601978,10.245558,3020192
26726,seafood,2017-08-27,5,5.298670,11.445668,16.342670,11.445668,3021974
26727,seafood,2017-08-28,5,1.914506,8.073844,12.953550,8.073844,3023756
26728,seafood,2017-08-29,5,1.306258,7.617987,12.674770,7.617987,3025538
26729,seafood,2017-08-30,5,3.952590,9.397840,14.650101,9.397840,3027320